const USERNAME_OR_PASSWORD_IS_NOT_VALID ='USERNAME_OR_PASSWORD_IS_NOT_VALID'
const USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS'
const USERNAEM_DOESNOT_EXISTS =  

module.exports = {
    USERNAME_OR_PASSWORD_IS_NOT_VALID,
    USERNAME_ALREADY_EXISTS
}