const USERNAME_OR_PASSWORD_IS_NOT_VALID ='USERNAME_OR_PASSWORD_IS_NOT_VALID'
const USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS'
const USERNAME_DOESNOT_EXISTS =  'USERNAME_DOESNOT_EXISTS'
const BAD_PASSWORD = "BAD_PASSWORD"
const AUTHORIZATION_FAILURE = "AUTHORIZATION_FAILURE"

module.exports = {
    USERNAME_OR_PASSWORD_IS_NOT_VALID,
    USERNAME_ALREADY_EXISTS,
    USERNAME_DOESNOT_EXISTS,
    BAD_PASSWORD,
    AUTHORIZATION_FAILURE
}